// Caregiver enters pairing code (generated by family) → bind self as paired_line_user_id
import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { bindFamily } from "@/lib/pairing";
import { isCloudEnabled } from "@/lib/supabase-server";
import { checkSameOrigin } from "@/lib/origin-check";
import { logAudit, getActorIp } from "@/lib/audit";
import { rateLimitAsync } from "@/lib/rate-limit";

export const runtime = "nodejs";

const CODE_REGEX = /^[A-HJ-NP-Z2-9]{6}$/i;

export async function POST(req: Request) {
  const ip = getActorIp(req);
  const csrf = checkSameOrigin(req);
  if (csrf) {
    logAudit({ action: "FORBIDDEN_ORIGIN", actorIp: ip, resourceType: "pairing", status: "forbidden" });
    return csrf;
  }
  if (!isCloudEnabled()) {
    return NextResponse.json({ error: "雲端服務未啟用" }, { status: 503 });
  }
  const session = await auth();
  const lineUserId = (session?.user as { lineUserId?: string } | undefined)?.lineUserId;
  if (!lineUserId) {
    return NextResponse.json({ error: "未登入" }, { status: 401 });
  }

  // Rate limit:防暴力枚舉 6 字元配對碼
  // 同一 IP 5 分鐘最多 5 次,同一登入帳號 5 分鐘最多 5 次
  // 用 async 版本 -> Upstash Redis 跨 Vercel instance 共享
  const ipRl = await rateLimitAsync(`pair-bind-ip:${ip ?? "noip"}`, { max: 5, windowMs: 5 * 60_000 });
  const userRl = await rateLimitAsync(`pair-bind-user:${lineUserId}`, { max: 5, windowMs: 5 * 60_000 });
  if (!ipRl.ok || !userRl.ok) {
    logAudit({
      action: "PAIRING_BIND_REJECT",
      actorLineUserId: lineUserId,
      actorIp: ip,
      resourceType: "pairing",
      status: "forbidden",
      metadata: { reason: "RATE_LIMIT" },
    });
    return NextResponse.json(
      { error: "嘗試次數過多,請 5 分鐘後再試" },
      { status: 429 }
    );
  }

  const body = (await req.json().catch(() => ({}))) as { code?: string };
  const code = (body.code ?? "").toUpperCase().trim();
  if (!CODE_REGEX.test(code)) {
    return NextResponse.json({ error: "配對碼格式錯誤" }, { status: 400 });
  }

  const result = await bindFamily(code, lineUserId);
  if (!result.ok) {
    logAudit({
      action: "PAIRING_BIND_REJECT",
      actorLineUserId: lineUserId,
      actorIp: ip,
      resourceType: "pairing",
      status: "forbidden",
      metadata: { reason: result.error },
    });
    const userMsg =
      result.error === "ALREADY_PAIRED_OR_EXPIRED"
        ? "配對碼已被使用或已過期，請家屬重新產生新碼"
        : "配對失敗";
    return NextResponse.json({ error: userMsg }, { status: 400 });
  }

  logAudit({
    action: "PAIRING_BIND",
    actorLineUserId: lineUserId,
    actorIp: ip,
    resourceType: "pairing",
    resourceId: result.pairing?.elder_id,
    status: "ok",
  });

  return NextResponse.json({
    ok: true,
    elderName: result.pairing?.display_name ?? null,
  });
}
